Add "No recipes found!" text when recipes list is empty
GianniGabriel/recipe-finder pull request #8
Opened 2022-03-26 14:29 UTC by HanHanzhi

![Screenshot 2022-03-26 at 10 28 47 PM](https://user-images.githubusercontent.com/62469674/160244006-9c17d4fb-23f4-4e6c-8cb8-4fda13a94961.png)
@GianniGabriel

2022-03-26 14:47 UTC, GianniGabriel requested changes
Nice work, one change requested before merging. Perform the requested changes, commit them to this branch, and @ me again so I can approve the new changes.

2022-03-26 14:47 UTC, GianniGabriel commented on src/components/layout/Search/SearchArea.module.css
> +  align-self: center;
Great job using `align-self` here! 👍

2022-03-26 14:47 UTC, GianniGabriel commented on src/components/layout/Search/SearchArea.module.css
> +  filter: drop-shadow(1px 1px 1px #413e3e);
I think the drop shadow is a bit too dark here. Try changing the `drop-shadow` color from `#413e3e` to `#9f9f9f`

2022-03-26 15:01 UTC, HanHanzhi commented
![Screenshot 2022-03-26 at 10 51 09 PM](https://user-images.githubusercontent.com/62469674/160245271-8e903f44-02f2-49a3-bca7-e81f069f127a.png)
@GianniGabriel

2022-03-26 16:53 UTC, GianniGabriel approved these changes
Branch ready to merge into main. Really nice stuff resolving the merge conflicts. But it's a good idea to not resolve any merge conflicts until your PR has been approved.

2022-03-27 05:17 UTC, HanHanzhi commented
@GianniGabriel Alright! will keep this in mind

2022-03-27 05:17 UTC, merged